apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-igye
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-igye@sha256:1e40ae1a9e55fa5b927f16ca7df0ac812bf2367a36cc517e4b515352eb0e5d89
        name: my-nodejs
        resources: {}
status: {}
